### PR TITLE
add segmentation part in 15 Computer Vision

### PR DESCRIPTION
**Pull request by DH-Diego**
Add segmentation part with consist style of classification part and fixed minor typos in previous parts.

### CODE REVIEW

**Comment by GokuMohandas** [comment]
this is a great contribution DH-Diego! I'll review it later this week but from a quick look, I think this may deserve its own notebook.

**Comment by DH-Diego** [comment]
So I’ll separate it with other suggested fix after your reciew

**Comment by mutouwl** [comment]
牛

**Comment by DH-Diego** [comment]
@GokuMohandas Hi, I'm wondering would you plan to review this pull request recently? So that we can merge the update.

**Comment by GokuMohandas** [comment]
hey @DH-Diego , sorry things have been crazy. I will separate it into its own notebook and send that for you to edit/approve (hopefully) over this weekend.

**Comment by GokuMohandas** [comment]
in the process of transferring everything to new repo so closing this for now and merging after move

**Pull request closed without merging**
